### ISSUE TITLE
Error when importing tensorflow_addons==0.10.0

### ISSUE THREAD

**Issue by nielsrolf** [tensorflow/addons#1846]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX 10.14.6
- TensorFlow version and how it was installed (source or binary): 2.1.0, installed with `pip install tensorflow`
- TensorFlow-Addons version and how it was installed (source or binary): 0.10.0, installed via pip
- Python version: 3.7.6
- Is GPU used? (yes/no): no

**Describe the bug**
When I try to import tensorflow_addons, I get the following error:
```
python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow_addons as tfa
/Users/<username>/miniconda3/envs/testenv/lib/python3.7/site-packages/tensorflow_addons/utils/ensure_tf_install.py:68: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.2.0 and strictly below 2.3.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.1.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<username>/miniconda3/envs/testenv/lib/python3.7/site-packages/tensorflow_addons/__init__.py", line 21, in <module>
    from tensorflow_addons import activations
  File "/Users/<username>/miniconda3/envs/testenv/lib/python3.7/site-packages/tensorflow_addons/activations/__init__.py", line 22, in <module>
    from tensorflow_addons.activations.rrelu import rrelu
  File "/Users/<username>/miniconda3/envs/testenv/lib/python3.7/site-packages/tensorflow_addons/activations/rrelu.py", line 28, in <module>
    rng: Optional[tf.random.Generator] = None,
AttributeError: module 'tensorflow_core._api.v2.random' has no attribute 'Generator'
>>> 
```

**Code to reproduce the issue**

I created my environment like this:
```
conda create -n testenv python=3.7.6
conda activate testenv
pip install --upgrade pip
pip install tensorflow==2.1.0
pip install tensorflow-addons==0.10.0
pip install tensorflow-estimator==2.1.0
```

In this environment, I cannot import tensorflow_addons.

**Other info / logs**

It works with `tensorflow-addons==0.8.3`

**Comment by WindQAQ** [comment]
Hi, `tensorflow_addons==0.10.0` works only on `tensorflow==2.2.0`. Please let me know if I missed anything. Thank you.

https://github.com/tensorflow/addons#python-op-compatibility-matrix
