### ISSUE TITLE
Troubles importing tensorflow_addons after build from source

### ISSUE THREAD

**Issue by vrince** [tensorflow/addons#747]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow version and how it was installed (2.0.0 pip):
- TensorFlow-Addons version and how it was installed (source):
- Python version: 3.7
- Is GPU used? (yes/no): yes

**Describe the bug**

After clean build from source `import tensorflow_addons as tfa` fails.

**Code to reproduce the issue**

```bash
# clone master (f445673d0f2001a7e002cda7ba8e413974390cec)
virtualenv -p python3 .env
source .env/bin/activate  
./configure.sh
bazel build build_pip_pkg
./build_pip_pkg.sh artifacts
pip install --force-reinstall artifacts/*.whl
```
Build is OK, `tensorflow_addons` ends up in the virtual env site-packages.

Test are passing example :

```bash
bazel test //tensorflow_addons/image:transform_ops_test
WARNING: /home/thomas/.cache/bazel/_bazel_thomas/8356422ad8f74fe8d549fa0b48b13455/external/local_config_tf/BUILD:2620:1: target 'libtensorflow_framework.so.2' is both a rule and a file; please choose another na
me for the rule
INFO: Analyzed target //tensorflow_addons/image:transform_ops_test (6 packages loaded, 179 targets configured).
INFO: Found 1 test target...
Target //tensorflow_addons/image:transform_ops_test up-to-date:
  bazel-bin/tensorflow_addons/image/transform_ops_test
INFO: Elapsed time: 49.639s, Critical Path: 49.52s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed successfully, 6 total actions
//tensorflow_addons/image:transform_ops_test                             PASSED in 49.5s

INFO: Build completed successfully, 6 total actions
```

So far so good.

But If I do a simple : 

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import tensorflow_addons as tfa
```

I get : 

```bash
Traceback (most recent call last):
  File "tensorflow_addons/play.py", line 10, in <module>
    from tensorflow_addons.image import transform_ops
  File "/home/thomas/dev/addons/.env/lib/python3.7/site-packages/tensorflow_addons/__init__.py", line 21, in <module>
    from tensorflow_addons import activations
  File "/home/thomas/dev/addons/.env/lib/python3.7/site-packages/tensorflow_addons/activations/__init__.py", line 21, in <module>
    from tensorflow_addons.activations.gelu import gelu
  File "/home/thomas/dev/addons/.env/lib/python3.7/site-packages/tensorflow_addons/activations/gelu.py", line 27, in <module>
    @tf.keras.utils.register_keras_serializable(package='Addons')
AttributeError: module 'tensorflow_core.keras.utils' has no attribute 'register_keras_serializable'
```

I am a little confuse cause the tests are running great and they do `import` tfa, I looked for specifics magic bazel could do to setup test env but found nothing ...

To warp up, I also try with tfa from pip (with exactly the same version of tf) in another virtual env and its importing correctly ... so I guess it's not related to tf / cuda / driver / blalblabla.

Thanks !

-----

Note: to make the `build_pip_pkg.sh` pass I hade to change line `19` to `PIP_FILE_PREFIX="bazel-bin/build_pip_pkg.runfiles/tensorflow_addons/"` cause there is no `__main__` folder ...

**Comment by seanpmorgan** [comment]
Hi @vrince `register_keras_serializable` was added after TF2.0 was released. You can either build 0.6 branch from source and it should work with TF2.0:
https://github.com/tensorflow/addons/tree/r0.6

Or compile master branch against TF2.1 release candidate.

**Comment by vrince** [comment]
Nice ! so I need to force tf nightly >= 2.1 will give a try ... Not sure why bazel test / build runs against 2.1 while wheel artifact in virtual env not but I'll dig a little more.

**Comment by vrince** [comment]
@seanpmorgan my very bad if I had have read the doc correctly it says `./build_pip_pkg.sh artifacts --nightly` ... and the `--nightly` **is** important ! Thanks.
